# Use an official Python runtime as a base image
FROM python:3.8-slim-buster

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /app
COPY . /usr/src/app

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org numpy gradio requests Pillow

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable for API Key (if needed)
# ENV API_KEY your_api_key_here

# Run app.py when the container launches
CMD ["python", "app.py"]
